---
  - name: install unzip and wget
    package:
      name:
        - unzip
        - wget
      state: present
      update_cache: yes
  - name: Download latest Wordpress
    get_url:
      url: https://wordpress.org/latest.tar.gz
      dest: /tmp/wordpress.tar.gz
  - name: extract wordpress
    unarchive:
      src: /tmp/wordpress.tar.gz
      dest: /tmp/
      remote_src: yes
  - name: find all files in /var/www/html
    find:
      paths: /var/www/html
      file_type: any
      recurse: yes
    register: html_files
  - name: Delete all files in /var/www/html
    file:
      path: "{{item.path}}"
      state: absent
    loop: "{{html_files.files}}"
  - name: move wordpress files to web root
    command: mv /tmp/wordpress/ /var/www/html
    args:
      creates: /var/www/html/wp-config-sample.php
  - name: set permission on wordpress directory
    file: 
      path: /var/www/html
      state: directory
      recurse: yes
      owner: www-data
      group: www-data
      mode: '0755'
  - name: Copy wp=config.php template
    template:
      src: wp-config.php.j2
      dest: /var/www/html/wp-config.php
      owner: www-data
      group: www-data
      mode: '0644'
