---
- name: update apt cache on ubuntu
  apt:
    update_cache: yes
  when: ansible_os_family == "Debian"

- name: install mysql-python
  package:
    name: python3-pymysql
    state: present
  when: ansible_os_family == "Debian"
