---
  - name: install php and required modules
    package:
      name:
        - php
        - php-mysql
        - php-curl
        - php-gd
        - php-mbstring
        - php-xml
        - php-xmlrpc
      state: present
      update_cache: true
  - name: restart the apache service
    service:
      name: apache2
      state: restarted
    when: ansible_os_family == "Debian"
