---
- name: Ensure Apache is installed
  apt:
    name: apache2
    state: present
  become: true
 
- name: Ensure web root exists
  file:
    path: /var/www/html
    state: directory
    owner: www-data
    group: www-data
    mode: '0755'
 
- name: Find and remove existing files in web root
  find:
    paths: /var/www/html/
    file_type: any
    recurse: yes
  register: html_files
 
- name: Delete all existing contents from web root
  file:
    path: "{{ item.path }}"
    state: absent
  loop: "{{ html_files.files }}"
 
- name: Download latest WordPress archive
  get_url:
    url: https://wordpress.org/latest.tar.gz
    dest: /tmp/wordpress.tar.gz
 
- name: Extract WordPress
  unarchive:
    src: /tmp/wordpress.tar.gz
    dest: /tmp/
    remote_src: yes
 
- name: Copy WordPress files to web root
  copy:
    src: /tmp/wordpress/
    dest: /var/www/html/
    owner: www-data
    group: www-data
    mode: '0755'
    remote_src: yes
 
- name: Set permissions for wp-config.php
  template:
    src: wp-config.php.j2
    dest: /var/www/html/wp-config.php
    owner: www-data
    group: www-data
    mode: '0644'
 
- name: Restart Apache
  service:
    name: apache2
    state: restarted
 
